### ISSUE TITLE
Crash when Clicking Keybinds in Settings.

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [matthe815/mmo-parties#34]
Upon trying to open the keybinds menu in settings, the game will instantly crash. doesn't matter if you open setting on the main menu or in a world.
Testing confirms removing this mod fixes the issue.

[crash-2023-01-02_14.20.52-client.txt](https://github.com/matthe815/mmo-parties/files/10333229/crash-2023-01-02_14.20.52-client.txt)

**Comment by matthe815** [comment]
Thank for you the bug report. I have confirmed the error to occur on 1.19.2.

**Comment by matthe815** [comment]
I have fixed it as per https://www.curseforge.com/minecraft/mc-mods/rpg-parties/files/4291735
