### ISSUE TITLE
Advice when having more health

### ISSUE THREAD

**Issue by ainlzj** [matthe815/mmo-parties#5]
1.16.5 Is it possible to change the gui to a simple ❤ 20 , the gui display is very uncomfortable when I have a lot of blood,
  Is it possible to add an avatar to it?

![屏幕截图 2022-08-18 014557](https://user-images.githubusercontent.com/66135518/185207661-2c39be0a-61a5-4963-8f2f-601382b8be3e.png)

**Comment by ainlzj** [comment]
![屏幕截图 2022-08-18 015153](https://user-images.githubusercontent.com/66135518/185208333-11f397dc-54d9-42fb-9d03-6b3ffa29ab69.png)  when more health

Armor is the same

**Comment by matthe815** [comment]
当然，我可以做这个。

**Comment by ainlzj** [comment]
你会中文？ 护甲其实也可以这样

**Comment by matthe815** [comment]
我懂一点中文  它通过屏幕的底部显示？

**Comment by ainlzj** [comment]
https://www.curseforge.com/minecraft/mc-mods/teams 这是类似的模组但是没有tp功能  他们的hud跟我说的差不多

**Comment by matthe815** [comment]
我理解。我会修复它

**Comment by ainlzj** [comment]
为什么我tp不了我的队员  当我指令写到/party tp 这里后并没有队友提升出来，手动输入后是会有五秒提升但没有传送

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/185229526-f40f8196-c255-444f-a33b-6cebae468a15.png)

**Comment by matthe815** [comment]
对不起，回复晚了 它应该自动显示一个名字，但它被打破了

**Comment by matthe815** [comment]
![image](https://user-images.githubusercontent.com/25229421/189208536-fe43ca21-ddf9-4867-a26b-184f056c812c.png)

**Comment by ainlzj** [comment]
是的，第一个是生命值，第二个是饥饿值，第三个是护甲值，如果你还想更好的话还可以添加个韧性，甚至可以这样
![image](https://user-images.githubusercontent.com/66135518/189246732-92392452-0ffb-476c-96d2-4bed88689fab.png)

或者这样上面再加个ID
![gui](https://user-images.githubusercontent.com/66135518/189248063-a2a7b67c-ec81-4c61-b079-c57e92613a2e.png)

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/193505937-0739f9b4-99ad-4c62-9f26-c54e332af487.png)

**Comment by ainlzj** [comment]
名字重叠

**Comment by ainlzj** [comment]
高版本的TP能用吗，我为什么TP不了

**Comment by matthe815** [comment]
我有一个正在制作的补丁

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/193708924-3b076404-5b95-4fcc-9880-19e604d01d55.png)
当我/party tp  tab键没有起作用 手打队员名字也是一样传送不了 (显示的是队员并未联机）      并且TP是默认开启的我没有关闭过
